// Developer Express Code Central Example:
// How to export a map to a file
// 
// To export a map to a file use one of the following methods.
// -
// MapControl.ExportToHtml
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToHtmltopic)
// - exports a map to a Html file
// - MapControl.ExportToImage
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToImagetopic)
// - exports a map as an image.
// - MapControl.ExportToMht
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToMhttopic)
// - exports a map to a Mht file.
// - MapControl.ExportToPdf
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToPdftopic)
// - exports a map to a Pdf file.
// - MapControl.ExportToRtf
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToRtftopic)
// - exports a map to a Rtf file.
// - MapControl.ExportToXls
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToXlstopic)
// - exports a map to a Xls file.
// - MapControl.ExportToXlsx
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToXlsxtopic)
// - exports a map to a Xlsx file.
// - MapControl.ExportToXps
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToXpstopic)
// - exports a map to a Xps file.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=T200511

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exporting.Properties {


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ((resourceMan == null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exporting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
