// Developer Express Code Central Example:
// How to export a map to a file
// 
// To export a map to a file use one of the following methods.
// -
// MapControl.ExportToHtml
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToHtmltopic)
// - exports a map to a Html file
// - MapControl.ExportToImage
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToImagetopic)
// - exports a map as an image.
// - MapControl.ExportToMht
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToMhttopic)
// - exports a map to a Mht file.
// - MapControl.ExportToPdf
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToPdftopic)
// - exports a map to a Pdf file.
// - MapControl.ExportToRtf
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToRtftopic)
// - exports a map to a Rtf file.
// - MapControl.ExportToXls
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToXlstopic)
// - exports a map to a Xls file.
// - MapControl.ExportToXlsx
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToXlsxtopic)
// - exports a map to a Xlsx file.
// - MapControl.ExportToXps
// (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToXpstopic)
// - exports a map to a Xps file.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=T200511

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exporting.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
