' Developer Express Code Central Example:
' How to export a map to a file
' 
' To export a map to a file use one of the following methods.
' -
' MapControl.ExportToHtml
' (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToHtmltopic)
' - exports a map to a Html file
' - MapControl.ExportToImage
' (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToImagetopic)
' - exports a map as an image.
' - MapControl.ExportToMht
' (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToMhttopic)
' - exports a map to a Mht file.
' - MapControl.ExportToPdf
' (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToPdftopic)
' - exports a map to a Pdf file.
' - MapControl.ExportToRtf
' (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToRtftopic)
' - exports a map to a Rtf file.
' - MapControl.ExportToXls
' (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToXlstopic)
' - exports a map to a Xls file.
' - MapControl.ExportToXlsx
' (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToXlsxtopic)
' - exports a map to a Xlsx file.
' - MapControl.ExportToXps
' (https://documentation.devexpress.com/#WPF/DevExpressXpfMapMapControl_ExportToXpstopic)
' - exports a map to a Xps file.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T200511

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
    Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

'        internal Resources()
'        {
'        }

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If (resourceMan Is Nothing) Then
                    Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property
    End Module
End Namespace
